// ============================================================
// REASONER.JS — Data-driven self-reasoning engine
// ============================================================

// ── PART 1: METRIC RELATIONSHIP MAP ──────────────────────────
// Each group defines a set of operationally-related metrics.
// When multiple metrics in a group are simultaneously anomalous,
// their co-movement is evidence for the group's named cause.
// Metric name matching is case-insensitive and whitespace-trimmed.

const METRIC_RELATIONSHIP_MAP = [

  {
    id: 'VACANCY_EVENT',
    name: 'Occupancy loss event',
    direction: 'income_down',
    minMatch: 2,
    signature: 'Multiple occupancy-related income lines dropped simultaneously — units came vacant, lease-up stalled, or a group of leases expired without renewal.',
    metrics: [
      'Less: Vacancy',
      'Market Rent',
      'Residential Rent',
      '(Loss)/Gain to Lease',
      'Delinquency',
      'Down Units',
      'Section 8',
    ],
  },

  {
    id: 'CONCESSION_PRESSURE',
    name: 'Leasing concession pressure',
    direction: 'income_down',
    minMatch: 2,
    signature: 'Multiple concession lines increased — property is offering incentives to attract or retain tenants, suggesting competition, soft demand, or lease-up pressure.',
    metrics: [
      'Concession',
      'Military Discount Concession',
      'Preferred Employer Concession',
      'First Responder Concession',
      'Employee Concession',
      'Marketing Concessions',
      'Resident Referral',
      'Brokers fee',
      'Month to Month',
    ],
  },

  {
    id: 'UTILITY_SPIKE',
    name: 'Utility cost spike',
    direction: 'expense_up',
    minMatch: 2,
    signature: 'Multiple utility lines spiked — driven by rate increase, seasonal consumption peak, equipment failure causing overconsumption, or a billing catch-up.',
    metrics: [
      'Electric Expense',
      'Electric Expense - vacant units',
      'Gas Expense',
      'Gas Expense - Vacant Units',
      'Water expense',
      'Sewer Expense',
      'Rubbish Removal/Sanitation',
      'Utility Billing',
      'Recoverable Elec/Gas/Water',
    ],
  },

  {
    id: 'TURNOVER_WAVE',
    name: 'Unit turnover wave',
    direction: 'expense_up',
    minMatch: 2,
    signature: 'Multiple turnover cost lines spiked — a wave of unit vacates triggered simultaneous make-ready costs across painting, cleaning, repairs, and supplies.',
    metrics: [
      'Unit Turnover - Carpet Cleaning & Repairs',
      'Unit Turnover - Painting',
      'Unit Turnover - Cleaning',
      'Unit Turnover - Bathroom Repairs',
      'Unit Turnover - Floor Repairs',
      'Unit Turnover - General Repairs',
      'Unit Turnover - Kitchen Repairs',
      'Unit Turnover - Supplies',
      'Unit Turnover - Appliances',
      'Unit Turnover - HVAC Repairs',
      'Unit Turnover - Resurfacing',
      'Unit Turnover - Countertop Repairs',
      'Unit Turnover - Vinyl Repairs',
      'Unit Turnover - Inspection Fees',
      'Paint & Plaster Contract',
      'Paint & Plaster Contract - Extra service',
    ],
  },

  {
    id: 'PAYROLL_INCREASE',
    name: 'Payroll cost increase',
    direction: 'expense_up',
    minMatch: 2,
    signature: 'Multiple payroll lines increased — new hire, annual raise cycle, bonus payout, overtime surge, or workers comp adjustment.',
    metrics: [
      'Payroll - Admin Assistant Property Manager',
      'Assistant Manager',
      'Payroll Taxes - Administrative',
      'Workers Comp - Administrative',
      'Health Insurance - Administrative',
      'Overtime - Administrative',
      'Bonus - Administrative',
      'Payroll - Leasing',
      'Leasing Consultant',
      'Payroll Taxes - Leasing',
      'Workers Comp - Leasing',
      'Health Insurance - Leasing',
      'Overtime - Leasing',
      'Bonus - Leasing',
      'Payroll - Maintenance',
      'Maintenance Tech',
      'Payroll Taxes - Maintenance',
      'Workers Comp - Maintenance',
      'Health Insurance - Maintenance',
      'Overtime - Maintenance',
      'Bonus - Maintenance',
      'Payroll - Property Manager',
      'Outside Services',
      'Severance Pay',
    ],
  },

  {
    id: 'MAINTENANCE_SURGE',
    name: 'Maintenance and repair surge',
    direction: 'expense_up',
    minMatch: 3,
    signature: 'Multiple repair and maintenance lines spiked — suggests a major system failure, deferred maintenance catch-up, seasonal preparation, or storm/weather damage.',
    metrics: [
      'Hot water Heaters',
      'Boiler Repairs & Maint',
      'HVAC Repairs & Maint',
      'HVAC Cleaning',
      'HVAC Contract',
      'Plumbing Repairs & Maint',
      'Leak Repair',
      'Roof Repairs & Maint',
      'Elevator Repairs & Maint',
      'Electrical Repairs & Maint',
      'Doors/Garage',
      'Mold',
      'Sewer and Drain Cleaning',
      'Fire Alarms',
      'Smoke Alarms',
      'Sprinklers',
      'Fire Extinguisher',
      'Lead Abatement & Testing',
      'Environmental Compliance',
    ],
  },

  {
    id: 'SEASONAL_WINTER',
    name: 'Winter seasonal cost pattern',
    direction: 'expense_up',
    minMatch: 2,
    signature: 'Winter-specific costs spiked together — consistent with cold weather driving heating, snow removal, and weatherization costs.',
    metrics: [
      'Gas Expense',
      'Gas Expense - Vacant Units',
      'Snow Removal Contract',
      'Snow Removal Contract - Extra service',
      'Hot water Heaters',
      'Boiler Repairs & Maint',
      'HVAC Repairs & Maint',
      'HVAC Contract',
    ],
  },

  {
    id: 'SEASONAL_SUMMER',
    name: 'Summer seasonal cost pattern',
    direction: 'expense_up',
    minMatch: 2,
    signature: 'Summer-specific costs spiked together — consistent with heat driving cooling costs, pool operation, and landscaping peak season.',
    metrics: [
      'Electric Expense',
      'Electric Expense - vacant units',
      'Pool Maintenance Contract',
      'Pool Maintenance Contract - Extra service',
      'Pool Repairs/Maintenance',
      'Pool Supplies',
      'Landscaping Contract',
      'Landscaping Contract - Extra service',
    ],
  },

  {
    id: 'LEASING_MARKETING_PUSH',
    name: 'Leasing and marketing push',
    direction: 'expense_up',
    minMatch: 2,
    signature: 'Multiple leasing and marketing costs increased — property launched a campaign to fill vacancies, suggesting occupancy pressure or a planned lease-up push for new units.',
    metrics: [
      'Online Marketing Expense',
      'Print Marketing',
      'Resident Events',
      'Resident Retention',
      'Other Marketing Expense',
      'Promotion and entertainment',
      'Brokers fee',
      'Resident Referral',
      'Marketing Software',
      'Signage Marketing',
    ],
  },

  {
    id: 'INSURANCE_TAX_RESET',
    name: 'Insurance or tax step-change',
    direction: 'expense_up',
    minMatch: 1,
    signature: 'Insurance or tax lines stepped up — consistent with annual policy renewal at higher premium, property tax reassessment, or new insurance requirement.',
    metrics: [
      'Property & Liability Insurance',
      'Umbrella Insurance',
      'Flood Insurance',
      'ELPI Insurance',
      'Real Estate Taxes',
      'Auto Insurance',
    ],
  },

  {
    id: 'BAD_DEBT_EVENT',
    name: 'Bad debt or delinquency event',
    direction: 'expense_up',
    minMatch: 1,
    signature: 'Bad debt or delinquency spiked — tenant(s) stopped paying rent, eviction proceedings were initiated, or a delinquency balance was written off.',
    metrics: [
      'Bad debts expense',
      'Bad Debt Recoveries',
      'Delinquency',
      'Legal L & T',
      'Broker of Record (L&T)',
      'Court Cost',
      'Late Fees',
    ],
  },

  {
    id: 'INCOME_RECOVERY',
    name: 'Income recovery or rebound',
    direction: 'income_up',
    minMatch: 2,
    signature: 'Multiple income lines recovered simultaneously — occupancy improved, concessions were reduced, or a rent increase took effect across units.',
    metrics: [
      'Market Rent',
      'Residential Rent',
      '(Loss)/Gain to Lease',
      'Less: Vacancy',
      'Late Fees',
      'Administrative Fee',
    ],
  },

  {
    id: 'COST_RECOVERY_SHIFT',
    name: 'Utility cost recovery change',
    direction: 'any',
    minMatch: 2,
    signature: 'Reimbursement lines changed — RUBS billing was adjusted, a new utility reimbursement program started or ended, or occupancy change affected the recoverable amount.',
    metrics: [
      'Reimbursed Water/Sewer',
      'Reimbursed Trash',
      'Reimbursed Utilities',
      'Reimbursed Renters Insurance',
      'Reimbursed Utility Fee',
      'Reimbursed Deposit Alternatives',
      'Other Reimbursed costs',
      'Rev Share',
    ],
  },

  {
    id: 'CONTRACT_REPRICING',
    name: 'Vendor contract repricing or new contracts',
    direction: 'expense_up',
    minMatch: 3,
    signature: 'Multiple contract lines increased simultaneously — annual vendor contract renewals came in higher, new service contracts were added, or a contract was restructured at a higher rate.',
    metrics: [
      'Exterminating Contract',
      'Pool Maintenance Contract',
      'Landscaping Contract',
      'Cleaning Contract',
      'Shuttle Contract',
      'Elevator Contract',
      'HVAC Contract',
      'Fire/Sprinkler Inspections & Monitoring Contract',
      'Fire Alarm Monitoring Contract',
      'Snow Removal Contract',
      'Valet Trash',
      'Security - Live Monitoring Contract',
      'Vent Cleaning',
      'Storage Unit Contract',
      'Washer & Dryer Rental Contract',
    ],
  },

];
